### ISSUE TITLE
dump modify command syntax change

### ISSUE THREAD

**Issue by zaidurrehman** [abelcarreras/aiida-lammps#1]
The syntax for `dump_modify format` has been changed. A new keyword `line` must be included for input files generation.  For example, old format

```
'dump_modify     aiida format "%16.10f %16.10f %16.10f"\n'
```

should be updated to 

```
'dump_modify     aiida format line "%16.10f %16.10f %16.10f"\n'
```

such as in [combinate script](https://github.com/abelcarreras/aiida-lammps/blob/fffabcb727ef8e3cae80068e8c28f69aa6229b10/plugins/jobs/lammps/combinate.py#L180)

**Comment by abelcarreras** [comment]
Thank you.
Now, master branch is a little outdated. So I will merge development 
branch to master soon after a little testing including this issue.

**Comment by zaidurrehman** [comment]
That will be great. Do you have any estimate of the merge?
It would be great if there is some documentation included as well.
I will be happy to contribute to this repo in any possible way.

**Comment by abelcarreras** [comment]
I'm a little busy these days and I have not much time to work on this.
I will try to do it next week. If you want you are welcome to try the development
branch in which dump_modify format is already fixed .

You are very welcome to contribute, I recently changed job and I really don't have 
much time for adding new potentials and support additional features of LAMMPS.
So just let me know in which degree of implication you would like to contribute.
(testing/coding/etc..)

If you are interested in some particular feature I can focus on it.
