### ISSUE TITLE
aiida_lammps plugin

### ISSUE THREAD

**Issue by Marla74** [abelcarreras/aiida-lammps#6]
I tried to install the plugin using AiiDa v.1 and received following error message "Could not find a version that satisfies the requirement aiida-lammps.1 (from versions: none". Is lammps plugin ready to be used?

**Comment by abelcarreras** [comment]
Hi,
In principle it should work, which version of aiida are you using exactly? If you are using master branch this plugin is tested for v1.0.0b1. I will check with the latest version of aiida

**Comment by Marla74** [comment]
Hi, 
I am using version 1.0.0.b3.

**Comment by Marla74** [comment]
Hi, 
after git clone it once again, the installation actually worked. Thank you!
